title: "Toru Takenaga"
url: "https://torutakenaga.com"
markdown: kramdown
theme: minima

# ナビに表示するページ
header_pages:
  - tango.md
  - kendo.md
  - research.md
  - contact.md

# プラグイン
plugins:
  - jekyll-feed
